import React from 'react';
import { HelpCircle, FileText, Send, Clock, BookOpen, AlertCircle } from 'lucide-react';

export default function Guide() {
  const faqs = [
    {
      q: "What is the RTI Act 2005?",
      a: "The Right to Information (RTI) Act is a law passed by the Parliament of India giving citizens the right to request information from 'public authorities' (government departments, ministries, municipal corporations, public sector undertakings, government-aided schools, etc.)."
    },
    {
      q: "How much does it cost to file an RTI?",
      a: "The standard application fee is ₹10. You can pay this using an Indian Postal Order (IPO), Demand Draft, Court Fee Stamp, or online payment (if filing online). Citizens belonging to the Below Poverty Line (BPL) category are exempt from this fee, provided they attach proof (copy of BPL Certificate)."
    },
    {
      q: "What is the timeline for receiving a response?",
      a: "The Public Information Officer (PIO) is legally mandated to reply within 30 days of receiving your application. If the requested information concerns the life or liberty of a person, it must be provided within 48 hours."
    },
    {
      q: "What should I do if I don't receive a reply in 30 days?",
      a: "If the PIO does not respond or rejects your application without valid reasons, you can file a 'First Appeal' within 30 days of the deadline. The First Appeal is addressed to the First Appellate Authority (FAA) inside the same department. There is no fee for filing a First Appeal in central departments."
    },
    {
      q: "How should I send the physical application?",
      a: "Always send your physical application via Registered Post or Speed Post. Keep the postal tracking receipt safe. This serves as proof of delivery, which is required if you need to file an appeal."
    },
    {
      q: "How do I file an online RTI?",
      a: "For Central Government ministries, departments, and public enterprises, you can file directly on the official portal: rtionline.gov.in. You can copy the questions generated by this tool and paste them into the text box on the portal."
    }
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center mb-12">
        <BookOpen className="h-10 w-10 text-indigo-600 mx-auto mb-3" />
        <h2 className="text-3xl font-extrabold text-slate-900">RTI Citizens Guide</h2>
        <p className="mt-3 text-lg text-slate-600 max-w-xl mx-auto">
          Understand your rights and learn how to draft and file effective RTI applications.
        </p>
      </div>

      {/* Rules and guidelines cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
        <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center space-x-3 mb-4 text-indigo-600">
            <FileText className="h-5 w-5" />
            <h3 className="font-bold text-lg text-slate-800">1. Draft Wisely</h3>
          </div>
          <ul className="space-y-3 text-slate-600 text-sm leading-relaxed">
            <li className="flex items-start">
              <span className="text-indigo-600 mr-2">•</span>
              <span><strong>Ask for records, not opinions:</strong> Do not write "Why has the road not been repaired?". Write "Provide the files and reasons recorded in writing for the delay in repairing the road."</span>
            </li>
            <li className="flex items-start">
              <span className="text-indigo-600 mr-2">•</span>
              <span><strong>Be specific:</strong> Avoid asking for "all details of road works since 2000". Ask for "work orders and bill payments for Mahatma Gandhi road from January 2024 to May 2025".</span>
            </li>
            <li className="flex items-start">
              <span className="text-indigo-600 mr-2">•</span>
              <span><strong>One topic per RTI:</strong> Keep your questions limited to one subject or incident to avoid delays.</span>
            </li>
          </ul>
        </div>

        <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center space-x-3 mb-4 text-indigo-600">
            <Send className="h-5 w-5" />
            <h3 className="font-bold text-lg text-slate-800">2. Sending Methods</h3>
          </div>
          <ul className="space-y-3 text-slate-600 text-sm leading-relaxed">
            <li className="flex items-start">
              <span className="text-indigo-600 mr-2">•</span>
              <span><strong>Offline via Post:</strong> Print your letter, sign it, attach a ₹10 Postal Order (IPO) payable to "Accounts Officer [Department Name]", and send via Speed Post to the PIO.</span>
            </li>
            <li className="flex items-start">
              <span className="text-indigo-600 mr-2">•</span>
              <span><strong>Online Portal:</strong> Go to <a href="https://rtionline.gov.in" target="_blank" rel="noopener noreferrer" className="text-indigo-600 font-semibold hover:underline">rtionline.gov.in</a>, register, choose the department, and paste your questions. You can pay the ₹10 fee via debit card or net banking.</span>
            </li>
            <li className="flex items-start">
              <span className="text-indigo-600 mr-2">•</span>
              <span><strong>BPL Category:</strong> If you are below the poverty line, tick the BPL box, omit payment, and attach a copy of your BPL card.</span>
            </li>
          </ul>
        </div>
      </div>

      {/* Warnings & Best practices */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-12 flex items-start space-x-3">
        <AlertCircle className="h-6 w-6 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <h4 className="font-bold text-amber-800 text-sm mb-1">Critical Advice: Avoid Rejection</h4>
          <p className="text-amber-700 text-xs leading-relaxed">
            Under Section 6(1) of the RTI Act, you do not need to give any reason for requesting information, nor do you need to provide detailed personal history (only your mailing address for the reply). 
            However, public authorities can refuse requests under Section 8 (exemptions, such as national security, intelligence agencies like IB/RAW, or personal privacy of third parties). Ensure your query does not violate citizen privacy or compromise public security.
          </p>
        </div>
      </div>

      {/* FAQs list */}
      <div className="space-y-6">
        <h3 className="font-bold text-xl text-slate-800 border-b pb-2 mb-4">Frequently Asked Questions</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-slate-50 p-5 rounded-lg border border-slate-200/80">
              <div className="flex items-start space-x-2">
                <HelpCircle className="h-5 w-5 text-indigo-500 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-slate-800 text-sm mb-2">{faq.q}</h4>
                  <p className="text-slate-600 text-xs leading-relaxed">{faq.a}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
